import {
  fetchRankedPlayers,
  fetchRosteredExtras,
  withRookies,
  withExtras,
  defaultSeason,
  MIN_RANKED,
} from '@/lib/espnPool.mjs'
import bundledPool from '@/data/nba-pool.json'
import rookies from '@/data/rookies-2026.json'

export type PoolPlayer = { name: string; position: string; ranking: number; auction_value: number }
export type PoolSource = 'espn' | 'fallback'

/** How long to wait on ESPN before falling back to the file in the bundle. */
const ESPN_TIMEOUT_MS = 8000

/**
 * The current player pool, live from ESPN with the bundle as a net.
 *
 * Shared by the two places that need it: `create-league`, which seeds a brand
 * new league from it, and `/api/admin/pool`, which hands it to the admin panel
 * so a league that already exists can be topped up with whatever has appeared
 * since it was created. They must not drift — a league seeded in September and
 * one topped up in November should end up with the same names.
 *
 * Live first so a league created today carries today's ranks without waiting
 * for a deploy; `data/nba-pool.json` (regenerated by
 * `scripts/fetch-espn-ranks.mjs`) is the net when ESPN is slow, down, or has
 * changed shape.
 *
 * Both paths go through `withRookies()`, which appends the draft class ESPN
 * has not ranked yet. The bundled file already carries them, so the merge is a
 * no-op there — it stays in the path so a bundle that has gone stale against a
 * newer rookie file still yields a complete pool. `MIN_RANKED` is checked on
 * ESPN's answer *before* the merge, so 60 local names can never disguise a
 * truncated fetch.
 *
 * `fetchRosteredExtras()` runs *alongside* the ranked fetch rather than after
 * it — it is a 180KB request against 15.5MB, so in parallel it costs no wall
 * clock at all, and the caller has 8s. It is also the one part allowed to fail
 * quietly: a pool short of Day'Ron Sharpe is worth having, no pool at all is
 * not. The bundled file already carries the supplement, so the fallback path
 * needs nothing extra.
 */
export async function loadPool(): Promise<{ players: PoolPlayer[]; source: PoolSource }> {
  const season = defaultSeason()
  const [rankedRes, extrasRes] = await Promise.allSettled([
    fetchRankedPlayers({ timeoutMs: ESPN_TIMEOUT_MS }),
    fetchRosteredExtras({ timeoutMs: ESPN_TIMEOUT_MS }),
  ])
  if (extrasRes.status === 'rejected') {
    console.error('loadPool: ESPN ownership fetch failed — ranked players only', extrasRes.reason)
  }
  const extras = extrasRes.status === 'fulfilled' ? extrasRes.value : []

  if (rankedRes.status === 'rejected') {
    console.error('loadPool: ESPN fetch failed — using the bundled pool', rankedRes.reason)
  } else {
    const live = rankedRes.value as PoolPlayer[]
    if (live.length >= MIN_RANKED) {
      return {
        players: withExtras(withRookies(live, rookies, season), extras) as PoolPlayer[],
        source: 'espn',
      }
    }
    console.error(`loadPool: ESPN returned only ${live.length} ranked players — using the bundled pool`)
  }

  return {
    players: withExtras(
      withRookies(bundledPool as PoolPlayer[], rookies, season),
      extras
    ) as PoolPlayer[],
    source: 'fallback',
  }
}
